name: Submit an SRT Sample
description: Help improve compatibility by sharing a sample SRT file.
title: "[SRT Sample] <Device Model>"

labels:
  - srt-sample

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve SRT compatibility!

        Please provide a **small SRT excerpt 5 subtitle entries)**.

        You can paste:
        - consecutive entries (recommended)
        - or any small representative sample

        If your SRT contains GPS coordinates or telemetry, you may redact them as long as the SRT structure remains valid.

  - type: input
    id: manufacturer
    attributes:
      label: Manufacturer
      placeholder: DJI, Autel, Potensic, FIMI, Holy Stone, etc.
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Device model
      placeholder: Mini 4 Pro
    validations:
      required: true

  - type: input
    id: firmware
    attributes:
      label: Firmware version (optional)
      placeholder: v01.00.0500

  - type: dropdown
    id: source
    attributes:
      label: Where does the SRT come from? (optional)
      options:
        - Standalone .srt file
        - Embedded subtitle track in MP4
        - Other (Please specify in the notes)
      placeholder: Embedded subtitle track in MP4

  - type: textarea
    id: sample
    attributes:
      label: Paste SRT sample (optional)
      description: |
        Paste somthing like 5 consecutive or random subtitle entries here.
        You can also leave this empty if you upload a file.
      render: text

  - type: checkboxes
    id: privacy_ack
    attributes:
      label: Privacy acknowledgment
      description: Please confirm before submitting.
      options:
        - label: I understand that SRT files may contain GPS coordinates and telemetry. I am aware that anything not redacted will be publicly visible in this GitHub issue.
    validations:
      required: true